### ISSUE TITLE
Is there anything wrong?

### ISSUE THREAD

**Issue by Chorer** [ohansemmanuel/Understanding-Flexbox#6]
>If you've written any text in the Japanese language, then this will be familiar! (for the record, I've never written any texts in Japanese). Japanese text is written from top-to-bottom and left-to-right! Not so weird, huh?

Maybe here it should be " Japanese text is written from top-to-bottom and righ-to-left! " instead of " Japanese text is written from top-to-bottom and left-to-right! " ?

**Comment by ohansemmanuel** [comment]
You're right. Will fix.
